### ISSUE TITLE
Extraction des opérations

### ISSUE THREAD

**Issue by chupi33** [cozy/cozy-banks#12]
Bonjour

Avez vous dans votre roadmap (je n'en ai pas trouvé) prévu de mettre à disposition une extraction des données. J'utilise un logiciel ([HomeBank](http://homebank.free.fr/fr/index.php) qui est openSource) pour gérer mes différents comptes. Je me balade donc sur les sites de mes différents comptes pour extraire sur chacun d'eux mes opérations afin de les importer dans le logiciel.

Il existe entre autres les formats [qif](https://fr.wikipedia.org/wiki/Quicken_Interchange_Format) et [ofx](https://fr.wikipedia.org/wiki/Open_Financial_Exchange).

J'ai bien tenté de regarder le code pour voir si ma demande à un sens mais je fais plutôt du Cobol (on ne rigole pas !!!).

Je continuerais d'utiliser vos services quelque soit votre réponse ;)

Merci pour votre boulot et bonne continuation.

**Comment by ptbrowne** [comment]
Bonjour,

Merci pour ton retour ! Du fait que la plateforme Cozy supporte plusieurs applications et plusieurs types de documents, nous nous basons sur du JSON en tant que format intéropérable de données.

Pour extraire les données d'un Cozy, nous utilisons ACH : https://github.com/cozy/ACH.

Pour extraire par exemple toutes les données bancaires d'un Cozy : 

```
$ ACH export io.cozy.bank.operations io.cozy.bank.accounts data-bank.json
```

Nous n'avons pas encore dans nos plans de supporter directement les formats qif mais ca ne devrait pas être très compliqué d'écrire un convertisseur JSON to qif en se basant sur des outils déjà existants : https://github.com/Kraymer/qifqif/blob/master/qifqif/qifile.py

**Comment by ptbrowne** [comment]
Salut chupi33, as tu réussi à extraire tes données, as tu besoin d'aide ?

**Comment by ptbrowne** [comment]
Je ferme, n'hésites pas si tu as encore besoin d'aide.

**Comment by Jean-Roc** [comment]
Bonjour @ptbrowne, est-ce qu'il serait possible d'avoir à minima un export txt/csv ? je trouve que ça dépasse le simple point technique : j'ai deux applis bancaires qui me propose chacune d'agréger tous mes comptes et qui permettent l'export dans de nombreux formats. A contrario j'ai un compte Cozy qui agrège mais qui est un cul de sac pour les données pour qui ne manipule pas npm et le parsing de json.
