### ISSUE TITLE
How to write our own bank providers?

### ISSUE THREAD

**Issue by niieani** [cozy/cozy-banks#13]
Hi devs!

I wanted to try out Cozy Banks, but noticed you don't really support many banks outside of France. I wrote a data-crawler for one of my banks in Poland, and wanted to integrate and contribute it.

But I can't see any of the providers in the repository.

Where can we find the code behind the providers, and how can we contribute? 

I'm sure crowdsourcing the providers would be a much better way to cover lots and lots of banks.

Cheers!

**Comment by niieani** [comment]
Hi Patrick, thanks for the quick reply!

My scraper is not OSS yet, as I need to make sure there are no accidentally exposed secrets in the repo before I make it available on GitHub.

I'll try to make the scraper OSS and make a konnector in spare time 👍

I assume I need to setup a local instance of Cozy Stack to test it out, right?

**Comment by ptbrowne** [comment]
> My scraper is not OSS yet, as I need to make sure there are no accidentally exposed secrets in the repo before I make it available on GitHub.

👌

> I'll try to make the scraper OSS and make a konnector in spare time 👍

Awesome :)

> I assume I need to setup a local instance of Cozy Stack to test it out, right?

You can test your konnector without a stack by running in [standalone mode](https://docs.cozy.io/en/dev/konnector/#cozy-konnector-template-and-standalone-mode); in this mode the calls to save data are mocked so you do not need a stack running.

The quickest way to have a cozy-stack running is the docker image : https://docs.cozy.io/en/cozy-stack/client-app-dev/#with-docker

**Comment by ptbrowne** [comment]
Hi @niieani , do you need some support ? We could arrange a chat/video if you want :)

**Comment by niieani** [comment]
Hi @ptbrowne, thanks for the follow up. Before writing the provider, I had first tested the features in the app and decided against using Cozy altogether (unfortunately).

A deal breaker for me is not having the ability to track cash spending, i.e. to manually add data points. For me, that limitation partially invalidates the whole point of tracking, as any reporting/analysis based on the data will be skewed.

If/when Cozy adds that, I'd happily go back to working on the bank provider.

**Comment by drazik** [comment]
Closing it because it's not active anymore. Thanks @niieani.
