### ISSUE TITLE
Assurance vie non remontée - Connecteur Crédit Mutuel

### ISSUE THREAD

**Issue by fchedemail** [cozy/cozy-banks#188]
Bonjour,

J'espère que c'est le bon repo pour faire ce signalement de bug :)
En connectant mes différents comptes bancaires, j'ai remarqué que celui du Crédit Mutuel remonte bien tous mes produits bancaires sauf un : une assurance vie. C'est étonnant, j'en ai deux et la première apparaît sans problème.

Pouvez-vous y faire quelque chose, où est-ce lié à Linxo ?

Merci d'avance,
Cordialement,

**Comment by ptbrowne** [comment]
C'est le bon repo :)

C'est quelque chose que l'on peut demander à Linxo, on te tient au courant, merci de nous avoir fait remonté le bug !

**Comment by drazik** [comment]
Bonjour @fchedemail. Nous utilisons maintenant les API de Budget Insight pour remonter les comptes bancaires. As-tu ton assurance vie dans banks maintenant ?

**Comment by fchedemail** [comment]
Bonjour @drazik, en effet c'est bon maintenant, on peut clôturer !

**Comment by drazik** [comment]
Merci !
