### ISSUE TITLE
L'analyse des comptes ne prend plus en compte les dépenses affectées à un autre mois

### ISSUE THREAD

**Issue by med93600** [cozy/cozy-banks#1943]
Bonjour,

J'ai l'impression que depuis la dernière version, la partie analyse ne prend plus en compte les dépenses affectées sur un mois différents

**Comment by clochix** [comment]
Bonjour @med93600,

Merci du signalement. Oui, effectivement nous avons constaté hier cette régression de la dernière version. Nous allons corriger cela rapidement :smile_cat:

**Comment by med93600** [comment]
Merci c'est corrigé dans la dernière version
