### ISSUE TITLE
Bug d'application et problème connexion Revolut

### ISSUE THREAD

**Issue by Plyliote** [cozy/cozy-banks#1973]
Bonjour, l'équipe de cozy tout d'abord je vous remercie pour votre système mais j'aimerai vous signalez des bugs pour que se système s'améliore.

Problème 1
1. j'ouvre l'application et il y a deux type de bug soi un écran qui charge soi un écran tous blanc.
![IMG_0188](https://user-images.githubusercontent.com/77437333/104577352-b09ba300-5659-11eb-8c4c-7129ab557af3.jpg)
![IMG_0187](https://user-images.githubusercontent.com/77437333/104577359-b2656680-5659-11eb-8265-e9f921ec5b75.jpg)

Problème 2 
1. je fait toute la démarche pour me connecter sur Revolut, j'accepte l'application Revolut donne l'accord vous valider et rien n'apparaît même en répétant cette démarche 5 fois je n'ai pas réussi a joindre mon compte Revolut.

**Smartphone 
 - Device: [iPhone 12]
 - OS: [ iOS14.3]
 - Browser [COZY BANKS application]

Merci de faire votre possible pour régler ses problème.

**Comment by clochix** [comment]
Bonjour @Plyliote,

Je vous remercie de nous avoir signalé ces soucis 😸 

Afin de nous aider à comprendre ce qui se passe, est-ce que vous pourriez envoyer un courriel à support chez cozycloud.cc en précisant l’adresse de votre Cozy ? Cela nous permettra de chercher dans les journaux de votre Cozy des explications aux difficultés que vous rencotrez.
