### ISSUE TITLE
Display a loader when a konnector status is different from an error?

### ISSUE THREAD

**Issue by flohhhh** [cozy/cozy-banks#2003]
It seems weird to me to display a loader in a different case of an error. 

With `done`status.
<img width="1485" alt="Capture d’écran 2021-02-09 à 17 49 20" src="https://user-images.githubusercontent.com/22611343/107398995-84602e80-6b00-11eb-9c09-cec76c056ed7.png">

See [file](https://github.com/cozy/cozy-banks/blob/c841e58f995694ca5004e8998de70e5d23fba020/src/ducks/balance/AccountRowLoading.jsx#L59)

**Comment by ptbrowne** [comment]
Yep, it seems that we could show a regular account row here.
