### ISSUE TITLE
Fetched 3.8Mo of data (for my cozy), at least twice

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-banks#2047]
When I go to https://mycozy-banks.mycozy.cloud/#/balances and check my network panel, I can see two requests on 
`data/io.cozy.bank.operations/_all_docs?include_docs=true` starting at almost the same time 
<img width="1289" alt="Capture d’écran 2021-03-26 à 19 32 06" src="https://user-images.githubusercontent.com/1107936/112677411-fe0e6a80-8e69-11eb-8b6d-3c372ee3da8c.png">

But as you can see, the result of this request is pretty heavy, and having to download it twice when we arrive on my balance page doesn't seems right.

**Comment by Crash--** [comment]
Oh, in fact, it seems  that this request is done periodically since even without navigating the request is dispatched. 

<img width="1411" alt="Capture d’écran 2021-03-26 à 19 35 03" src="https://user-images.githubusercontent.com/1107936/112677832-7d9c3980-8e6a-11eb-81a6-85d5c6d2b306.png">

**Comment by Crash--** [comment]
In fact, banks is making periodically all  the request on all_docs whatever the doctype is 

<img width="1410" alt="Capture d’écran 2021-03-26 à 19 37 33" src="https://user-images.githubusercontent.com/1107936/112678102-d66bd200-8e6a-11eb-8112-8cc58146f4be.png">


Is it attended?

**Comment by ptbrowne** [comment]
@flohhhh To close automatically an issue from a PR, "fix #<issue number>" is necessary ;)
