### ISSUE TITLE
useFullyLoadedQuery re-render loop

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-banks#2133]
Needs to be investigated, but when deploying 1.31.0 in production we had on a few cozies (mine & fab one) a freeze on the home page of Banks. It seems that `useFullyLoadedQuery` was looping, so the Balance component was re-render without stoping resulting in a browser crash. 

We reverted at least in emergency ae343e0a98978be29a5277ac8f10a51f24395ed7

**Comment by ptbrowne** [comment]
Fixed by d5984880387486246c7417202dc8a7524e9371de
