### ISSUE TITLE
Improve indexes ordre for queries

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-banks#2209]
Suite à https://github.com/cozy/cozy-banks/pull/2205#discussion_r689359048 on pourrait changer l'ordre des index https://github.com/cozy/cozy-banks/blob/master/src/ducks/transactions/queries.js#L45.

Par contre cela impliquerait une nouvelle création d'index, et donc potentiellement un temps un peu couteux pour les anciens utilisateurs.

Une idée serait de le faire en même temps que le changement d'adapteur Pouch (voir https://github.com/cozy/cozy-banks/pull/2205#discussion_r689273215 et https://github.com/cozy/cozy-drive/pull/2399 sur Drive) qui nécessite aussi une nouvelle création d'index.

On pourrait donc avertir les utilisateurs de ces changements.

**Comment by Crash--** [comment]
On vient juste d'ajouter les warmup queries avec la création de nouveaux index. J'ai l'impression qu'on va créer les index même pour les anciens utilisateurs, non ? Si c'est le cas, c'est peut-être justement le bon moment pour le faire ?

**Comment by JF-Cozy** [comment]
Faire le changement d'ordre, l'adapteur Pouch, ou les deux ?

**Comment by Crash--** [comment]
le changement d'ordre

**Comment by JF-Cozy** [comment]
Ok effectivement on a déjà touché avec les warmup. Je m'en occupe :)
