### ISSUE TITLE
remove ACH from deps of banks

### ISSUE THREAD

**Issue by trollepierre** [cozy/cozy-banks#2323]
ACH n'est pas sur toutes les app + le fait que ce soit marqué "global" dans la doc me fait dire qu'on devrait même supprimer ACH des dep de banks

_Originally posted by @JF-Cozy in https://github.com/cozy/cozy-banks/pull/2316#discussion_r802704923_

please read the thread :pray:

**Comment by PolariTOON** [comment]
Fixed in #2418
