### ISSUE TITLE
Install "banks" on cozy-stack

### ISSUE THREAD

**Issue by zaggash** [cozy/cozy-banks#2341]
Not sure why this is not working.

cozy-stack -c cozy.yaml apps install --domain "mydomain" banks 'https://github.com/cozy/cozy-banks/archive/refs/tags/1.42.0.tar.gz'

Any chance we can get is working on a selfhosted instance ?

**Comment by clochix** [comment]
Hello @zaggash,

Looks like the URL of your server is missing after `--domain`.
Could you try `cozy-stack apps install --domain [the URL of your Cozy] banks 'https://github.com/cozy/cozy-banks/archive/refs/tags/1.42.0.tar.gz'`.

Also please keep in mind that you can install the Bank application on a self hosted server, but you won't be able to use our konnectors to import your bank operations.

To import bank data, we use a third party service, which is not available to self hosted users.

For any question regarding self hosting, please [ask on our forum](https://forum.cozy.io/c/francais/hebergement/43).
