### ISSUE TITLE
Import/export feature mentioned in documentation but nowhere to be found in UI

### ISSUE THREAD

**Issue by zdimension** [cozy/cozy-banks#2641]
![image](https://user-images.githubusercontent.com/4533568/229379827-59b381e5-e530-4dd9-9192-10aadb1b9ee6.png)

On Cozy Banks (Cozy Cloud):

![image](https://user-images.githubusercontent.com/4533568/229379841-ca8ea882-3718-47a6-8632-439c84c96436.png)

**Comment by clochix** [comment]
The documentation ha been published on Friday but we waited this morning to publish the feature.

Import and export are now available :-)

(also, please don't use issues for support requests. It's better to send an email to support at cozycloud.cc or ask in the forum https://forum.cozy.io/ )
