### ISSUE TITLE
Add information manually

### ISSUE THREAD

**Issue by theel0ja** [cozy/cozy-banks#278]
Well, because I don't live in France

**Comment by drazik** [comment]
Hello @theel0ja, thanks for the issue. Can you tell us more about what you want to be able to do ?

**Comment by theel0ja** [comment]
I mean that it should have ability to type in data manually if bank doesn't
support it.

**Comment by drazik** [comment]
We don't support it for the moment and I don't think we are going to add it. Cozy is based on a "connectors" mechanism. A connector is a NodeJS program that connects to a provider and fetches the user's data from it.

We are of course open to community contributions, so it would be great if you can write your own connector. We are available to help you if you need it.

You can see https://github.com/konnectors/cozy-konnector-bank-cragr, which is a connector for a french bank, but the logic should be the same for yours. You can also see all our others connector at https://github.com/konnectors, and the documentation about how to write a connector at https://docs.cozy.io/en/dev/konnector/. You can also ping us, of course.

Thank you.

**Comment by drazik** [comment]
Closing it because it's not active.
