### ISSUE TITLE
Display issue with the pie chart

### ISSUE THREAD

**Issue by LudovicRousseau** [cozy/cozy-banks#292]
I have a problem with the text displayed when I move the mouse pointer on the different pie charts: the text is mixed with the text bellow and is not readable. See attached screen shot.

 ![cozy](https://user-images.githubusercontent.com/398496/42580667-57f4dd40-852b-11e8-99d5-0b584fd684a0.png)

I use Firefox 61.0.1 on macOS High Sierra. Tell me if you need more details.
Thanks for Cozy.

**Comment by drazik** [comment]
Thank you for the issue :) we will look at it and fix it asap

**Comment by drazik** [comment]
This has been fixed. Thanks again @LudovicRousseau.
