### ISSUE TITLE
Utiliser un seul document settings au lieu d'une collection

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-banks#337]
Actuellement nous sauvegardons les préférences de l’utilisateur et d'autres informations dans un document `io.cozy.bank.settings`. Pour pouvoir récupérer ce document nous récupérons une collection de  `io.cozy.bank.settings` et on prend le 1er document (on espère qu'il y en a qu'un seul)

On peut voir ce type de code:
```
export const getSettingsFromCollection = col =>
  merge(DEFAULTS_SETTINGS, get(col, 'data[0]'))
```

Je propose que l'on nomme ce document plutôt que l'id soit généré par couchdb.

On pourrait alors demander à la stack seulement un document plutôt qu'une collection.

**Comment by ptbrowne** [comment]
> Je propose que l'on nomme ce document plutôt que l'id soit généré par couchdb.

Tu propose de setter l'_id à la main `{ _id: 'userSettings', ...DEFAULT_SETTINGS }` ? Ca m'irait. Si on a pas à rajouter un attribut `name` + 1 index, c'est plus simple :)

**Comment by ptbrowne** [comment]
Pas vraiment de gain à court long terme. Ce qu'on a en ce moment fonctionne. A garder en tête si jamais cela devient trop compliqué.
