### ISSUE TITLE
Le bouton Inclure les revenus de la vue Catégorisation ne rafraîchit pas le graphe

### ISSUE THREAD

**Issue by massyas** [cozy/cozy-banks#425]
Bonjour,
Dans cozy-banks (version mobile et Android) le switch permettant d'Inclure les revenus ne rafraîchit pas le graphe lorsqu'il change d'état.  
**Scénario:** 
1. Ouvrir Cozy-banks sur la vue Catégorisation (Inclure les revenus est désactivé)
2. Cliquer sur Inclure les revenus pour l'activer.   

**Résultat :**
Le bouton change d'état mais le graphique affiche toujours la même information

**Résultat attendu:**
Le bouton change  d'état et le graphique affiche la répartition en incluant les revenus.
**By-pass:**
3. Ouvrir une catégorie
4. Revenir en arrière avec le bouton précédent
=> Le graphique est maintenant à jour

**Comment by drazik** [comment]
Bonjour @massyas, merci d'avoir prit le temps d'ouvrir cette issue. Nous allons essayer de reproduire le problème afin de le corriger. Nous vous tiendrons au courant de l'évolution.

**Comment by drazik** [comment]
Bonjour @massyas, ce soucis a été traité et le fix est déployé en production. Merci encore !
