### ISSUE TITLE
Suppression de compte bancaire non pérenne

### ISSUE THREAD

**Issue by hmsuchier** [cozy/cozy-banks#823]
Bonjour,
 Merci pour cette application très utile. Je constate cependant un bug : lorsque je souhaite supprimer un compte en banque de la liste des comptes qui sont affichés (Paramêtres -> Comptes -> [compte concerné] -> Effacer -> Confirmer la suppression), il réapparaît le lendemain. La suppression n'est pas pérenne.
Merci

**Comment by drazik** [comment]
Bonjour,

Ce comportement est dû au fait que ton connecteur bancaire est toujours présent. Lorsqu'il tourne le lendemain, il ramène à nouveau le compte que tu as supprimé la veille.

C'est indiqué dans la modale de confirmation lors de la suppression d'un compte bancaire:

![image](https://user-images.githubusercontent.com/1606068/51691818-ce4e4880-1ffb-11e9-9c10-e4cccac67560.png)

**Comment by ptbrowne** [comment]
Pour quelle raison supprime tu le compte ? Est ce que c'est un compte que tu ne veux pas voir ?

**Comment by hmsuchier** [comment]
Merci pour vos réponses. Il s'agit d'un compte sur lequel j'ai une procuration. Mais il ne fait pas partie de ma comptabilité personnelle, du coup ça perturbe un peu mes chiffres.

**Comment by ptbrowne** [comment]
Peut être que la fonctionnalité des groupes peut t'aider ? Tu ne pourras pas utiliser les groupes automatiques mais avec un nouveau groupe contenant seulement les groupes qui t'intéressent, peut être que tu t'y retrouveras mieux dans tes chiffres :)

**Comment by hmsuchier** [comment]
J'avoue n'avoir peut être pas assez creusé les fonctionnalités. Je vais m'y
intéresser de plus près. Encore merci !

Le jeu. 24 janv. 2019 à 19:37, Patrick Browne <notifications@github.com> a
écrit :

**Comment by ptbrowne** [comment]
:) Je ferme cette issue, n'hésites pas à la rouvrir si besoin.
